services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: countries
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  get_data:
    build:
      context: ./src
    command: ["python", "get_data.py"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/countries
      - DATA_SOURCE=wikipedia
    depends_on:
      db:
        condition: service_healthy

  print_data:
    build:
      context: ./src
    command: ["python", "print_data.py"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/countries
      - DATA_SOURCE=wikipedia
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: 